(function(){
'use strict';
const css='.agenda{display:grid;gap:16px}.agenda-hero{display:flex;justify-content:space-between;gap:18px;padding:20px 22px;border-radius:18px;background:linear-gradient(135deg,#064b87,#0072ce);color:#fff}.agenda-hero h2{font-size:25px;margin:4px 0}.agenda-kicker{font-size:12px;font-weight:900;letter-spacing:.08em;text-transform:uppercase;opacity:.8}.agenda-sub,.agenda-date{font-size:13px;line-height:1.45;opacity:.86}.agenda-date{text-align:right;font-weight:800}.agenda-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.agenda-metric,.agenda-item{appearance:none;text-align:left;border:1px solid var(--border);background:#fff;cursor:pointer}.agenda-metric{border-radius:15px;padding:15px;box-shadow:var(--shadow)}.agenda-metric:hover,.agenda-item:hover{border-color:var(--blue2);background:#f7fbff}.agenda-metric strong{display:block;font-size:29px;line-height:1;color:#123c69}.agenda-metric span{display:block;margin-top:7px;font-size:12px;font-weight:850;color:#64748b}.agenda-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;align-items:start}.agenda-card{background:#fff;border:1px solid var(--border);border-radius:18px;padding:18px;box-shadow:var(--shadow);min-width:0}.agenda-head{display:flex;justify-content:space-between;gap:12px;margin-bottom:12px}.agenda-title{font-size:16px;font-weight:900;color:#123c69}.agenda-note{font-size:12px;color:#64748b;margin-top:3px}.agenda-action{border:0;background:none;color:var(--blue);font-size:12px;font-weight:900;cursor:pointer;white-space:nowrap}.agenda-list{display:grid;gap:9px}.agenda-item{width:100%;display:flex;justify-content:space-between;gap:12px;border-radius:12px;padding:12px}.agenda-main{min-width:0}.agenda-item-title{display:block;font-size:13px;font-weight:900;color:#1e293b;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.agenda-meta{display:block;font-size:11px;color:#64748b;line-height:1.4;margin-top:4px}.agenda-empty{text-align:center;padding:22px 12px;color:#64748b;font-size:13px;background:#f8fafc;border-radius:12px}.agenda-summary{display:flex;align-items:center;gap:10px;padding:12px;border-radius:12px;background:#f0f7ff;border:1px solid #d5e9fb}.agenda-summary strong{font-size:22px;color:#005aa9}.agenda-summary span{font-size:12px;color:#47627e;line-height:1.35}@media(max-width:850px){.agenda-metrics{grid-template-columns:repeat(2,1fr)}.agenda-grid{grid-template-columns:1fr}}@media(max-width:520px){.agenda-hero{display:block;padding:17px}.agenda-hero h2{font-size:22px}.agenda-date{text-align:left;margin-top:12px}.agenda-metrics{gap:9px}.agenda-metric,.agenda-card{padding:13px}.agenda-item-title{white-space:normal}}';
const style=document.createElement('style');style.id='dgie-agenda-style-2026-08-03';style.textContent=css;document.head.appendChild(style);
const esc=v=>typeof escapeHtml==='function'?escapeHtml(v):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
function list(name){try{const v=eval(name);return Array.isArray(v)?v:[]}catch(_e){return []}}
function zone(x){const z=Number(x?.zona||0);if(z)return z;const id=Number(x?.estId||x?.establecimiento_id||0);try{return id&&typeof zonaEstablecimiento==='function'?Number(zonaEstablecimiento(id)||0):0}catch(_e){return 0}}
function school(x){const id=Number(x?.estId||x?.establecimiento_id||0),e=list('ESTABS').find(v=>Number(v.id)===id);return x?.est||x?.establecimiento||e?.n||'Establecimiento'}
function time(v){if(!v)return 0;const p=Date.parse(v);if(Number.isFinite(p))return p;const m=String(v).match(/(\d{1,2})\/(\d{1,2})\/(\d{2,4})/);return m?new Date(Number(m[3])<100?2000+Number(m[3]):Number(m[3]),Number(m[2])-1,Number(m[1])).getTime():0}
function osState(o){try{return norm(typeof getEstadoOS==='function'?getEstadoOS(o):o?.estado)}catch(_e){return norm(o?.estado)}}
function claimState(r,os){try{return norm(typeof estadoReclamoCanon==='function'?estadoReclamoCanon(r,os):r?.estado)}catch(_e){return norm(r?.estado)}}
function rank(x){const p=norm(x?.prio||x?.prioridad);return ['critico','critica'].includes(p)?0:['alto','alta'].includes(p)?1:['medio','media'].includes(p)?2:3}
function pendingMessage(c,z){const dest=Array.isArray(c?.destinatarios)?c.destinatarios:[],zones=(c?.zonas||[]).map(Number),isFor=dest.some(d=>norm(d?.tipo||d?.rol)==='inspector'&&Number(d?.zona)===z)||c?.alcance==='general'||(c?.alcance==='zona'&&zones.includes(z));if(!isFor)return false;const states=c?.estados||{},state=states[`inspector:${z}`]||states[String(z)]||{};return ['notificacion','comunicado'].includes(norm(c?.tipo))?state.estado!=='visto':state.estado!=='completado'}
function values(){const z=Number(currentUser?.zona||0),os=list('OS_ZONA').filter(o=>zone(o)===z),claims=list('RECLAMOS_ZONA').filter(r=>zone(r)===z),open=claims.filter(r=>!['finalizado','finalizada','anulado','anulada','derivado','derivada'].includes(claimState(r,os))),priority=open.filter(r=>rank(r)<2).sort((a,b)=>rank(a)-rank(b)||time(a?.fecha)-time(b?.fecha)),active=os.filter(o=>['pendiente','trabajando','en ejecucion','en_ejecucion'].includes(osState(o))).sort((a,b)=>time(a?.fecha)-time(b?.fecha)),now=new Date(),start=new Date(now.getFullYear(),now.getMonth(),now.getDate()).getTime(),visits=list('INTERVENCIONES').filter(i=>zone(i)===z&&!i?.eliminado&&time(i?.fechaHora||i?.fecha)>=start&&time(i?.fechaHora||i?.fecha)<start+86400000),messages=list('COMUNICACIONES').filter(c=>pendingMessage(c,z)).length;return {z,priority,active,visits,messages}}
window.irDesdeAgenda=function(tab){const tabs=window.dgieTabsForUser?.(currentUser)||[],i=tabs.indexOf(tab);if(i>=0)window.renderTab(i)};
function rowClaim(r){const critical=rank(r)===0;return `<button class="agenda-item" onclick="irDesdeAgenda('Reclamos')"><span class="agenda-main"><span class="agenda-item-title">${esc(school(r))}</span><span class="agenda-meta">${esc(r?.numero||'Reclamo')} · ${esc(r?.rubro||r?.titulo||'Sin rubro')} · ${esc(r?.fecha||'Sin fecha')}</span></span><span class="badge ${critical?'b-danger':'b-warn'}">${critical?'Crítico':'Alto'}</span></button>`}
function rowOS(o){const work=['trabajando','en ejecucion','en_ejecucion'].includes(osState(o));return `<button class="agenda-item" onclick="irDesdeAgenda('Órdenes de servicio')"><span class="agenda-main"><span class="agenda-item-title">${esc(school(o))}</span><span class="agenda-meta">O.S. ${esc(o?.numero||'—')} · ${esc(o?.rubro||o?.titulo||'Sin rubro')} · ${esc(o?.fecha||'Sin fecha')}</span></span><span class="badge ${work?'b-info':'b-warn'}">${work?'Trabajando':'Pendiente'}</span></button>`}
window.renderAgendaInspector=function(c){if(!c||currentUser?.role!=='inspector')return;const d=values(),now=new Date(),date=now.toLocaleDateString('es-AR',{weekday:'long',day:'numeric',month:'long'}),hello=now.getHours()<12?'Buen día':now.getHours()<19?'Buenas tardes':'Buenas noches';c.innerHTML=`<div class="agenda"><section class="agenda-hero"><div><div class="agenda-kicker">Agenda · Zona ${d.z}</div><h2>${hello}, ${esc(currentUser?.name||'Inspector')}</h2><div class="agenda-sub">Lo que necesita atención para organizar la jornada.</div></div><div class="agenda-date">${esc(date.charAt(0).toUpperCase()+date.slice(1))}</div></section><section class="agenda-metrics">${[['Reclamos',d.priority.length,'Reclamos críticos o altos'],['Órdenes de servicio',d.active.length,'O.S. activas'],['Intervenciones',d.visits.length,'Visitas registradas hoy'],['Comunicaciones',d.messages,'Comunicaciones pendientes']].map(x=>`<button class="agenda-metric" onclick="irDesdeAgenda('${x[0]}')"><strong>${x[1]}</strong><span>${x[2]}</span></button>`).join('')}</section><section class="agenda-grid"><article class="agenda-card"><div class="agenda-head"><div><div class="agenda-title">Atención prioritaria</div><div class="agenda-note">Reclamos abiertos críticos y altos de tu zona.</div></div><button class="agenda-action" onclick="irDesdeAgenda('Reclamos')">Ver reclamos</button></div><div class="agenda-list">${d.priority.length?d.priority.slice(0,6).map(rowClaim).join(''):'<div class="agenda-empty">No hay reclamos críticos ni altos pendientes.</div>'}</div></article><article class="agenda-card"><div class="agenda-head"><div><div class="agenda-title">Órdenes en marcha</div><div class="agenda-note">Pendientes y trabajando, primero las más antiguas.</div></div><button class="agenda-action" onclick="irDesdeAgenda('Órdenes de servicio')">Ver O.S.</button></div><div class="agenda-list">${d.active.length?d.active.slice(0,6).map(rowOS).join(''):'<div class="agenda-empty">No hay órdenes activas en este momento.</div>'}</div></article>${[['Actividad de hoy','Visitas cargadas durante la jornada.','Intervenciones',d.visits.length,d.visits.length===1?'visita registrada hoy':'visitas registradas hoy'],['Mensajes y pedidos','Comunicaciones que requieren una acción.','Comunicaciones',d.messages,d.messages===1?'comunicación pendiente':'comunicaciones pendientes']].map(x=>`<article class="agenda-card"><div class="agenda-head"><div><div class="agenda-title">${x[0]}</div><div class="agenda-note">${x[1]}</div></div><button class="agenda-action" onclick="irDesdeAgenda('${x[2]}')">Abrir</button></div><div class="agenda-summary"><strong>${x[3]}</strong><span>${x[4]}</span></div></article>`).join('')}</section></div>`};
const tabsPrev=window.dgieTabsForUser;window.dgieTabsForUser=function(user){const tabs=tabsPrev?tabsPrev(user):[];return user?.role==='inspector'&&!tabs.includes('Agenda')?['Agenda',...tabs]:tabs};
const renderPrev=window.renderTab;window.renderTab=function(i){if(currentUser?.role==='inspector'){const tabs=window.dgieTabsForUser?.(currentUser)||[];if(tabs[i]==='Agenda'){buildTabs(tabs);setActiveTab(i);hideGlobal();currentFichaId=null;window.renderAgendaInspector(document.getElementById('main-content'));return}}return renderPrev?renderPrev(i):undefined};
})();